### PR TITLE
Update cookbook to work with Chef 17

### PR DESCRIPTION
**Pull request by damacus**
# Description

- Increase the supported version of Chef to Chef 16

  This is inline with our support policies, allowing us to use the newest Chef features

- Remove dependency on the deprecated Windows cookbook
- Convert to modern custom resources
- Remove the default recipe
- Remove default_spec as we no longer have a default recipe
- Use the Chef `execute` and `directory` resources rather than Ruby methods
- Pull Windows helpers from the Windows cookbook and fix them to work in this cookbook

  As the Windows cookbook is no longer maintained many of the methods we used were deprecated
  in Ruby 2.7 but were never fixed. These methods have now been removed in Ruby 3.0

- Move resource documentation to the documentation/resource directory.
- Update README to reflect new usage

## Issues Resolved

None posted, bu this cookbook was a little busted with Chef17's release

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by Xorima — APPROVED** [review]

**Review by bmhughes — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [4.0.0](https://github.com/sous-chefs/seven_zip/releases/tag/4.0.0)

**Comment by serge-salamanka-1pt** [comment]
just broke my stable for years env, guys!

**Comment by serge-salamanka-1pt** [comment]
i depend on https://supermarket.chef.io/cookbooks/ark#dependencies that is taking the latest `seven_zip`

**Comment by serge-salamanka-1pt** [comment]
solved by introducing version limit in my cookbook:
`depends 'seven_zip', '~> 3.2.0'`

**Comment by serge-salamanka-1pt** [comment]
I hope this restriction for Chef was really needed to implement some fantastic feature for such a utility cookbook.

Nightmare.

**Comment by Xorima** [comment]
Hi @serge-salamanka-1pt 

We are working on ensuring compatibility of all our cookbooks with Chef 17, this was the first one next up is ark.
I am unsure what you mean by 
> I hope this restriction for Chef was really needed to implement some fantastic feature for such a utility cookbook.
This cookbook is owned by sous-chefs who are a community of volunteers who give up their free time to help maintain these cookbooks. 

It has been recommended best practice to pin dependencies for a while, we follow semver so people know when we are making a non-backwards compatible breaking change. 

You can see our Cookbook Support Policy: https://sous-chefs.org/docs/cookbook-support/ 

Kind Regards,
Jason Field
Sous-Chefs Board Member

**Pull request merged**
